Pipeline rewritten in python3
adsabs/ADSAffilPipeline pull request #30
Opened 2020-12-04 20:07 UTC by seasidesparrow

Major changes:

- Rewrite of all string-handling routines. All "strings" that it will see are coming from Solr and are thus unicode-clean, meaning all of the previous string handling logic could be (and was) removed.
- Removed all code related to sklearn and affiliation identification that used it.
- New app.function written to attempt a simple "bag of words/clauses" matching to user input strings. (This functionality is intended for a future API where users can try to ID an affiliation string.)
- comprehensive unittest suite (that actually works now!)
- uses adsputils==1.2.8. Requirements/dev-requirements were drastically simplified.

2020-12-14 16:46 UTC, seasidesparrow commented
To the reviewer: please pay attention to how I'm initializing (adict, cdict) in tasks.py.  These are large dictionaries (>> 100MB) and I need to make sure they're initialized once and only once when the celery workers are initialized.  Have I done that correctly here?

2021-01-22 18:08 UTC, kelockhart requested changes
Looks pretty good! Most of my suggestions are fairly small things to make the code more readable/consistent. Let me know if you want to chat about my suggestions, if that's easier or if my notes are unclear.

2021-01-22 18:08 UTC, kelockhart commented on ADSAffil/tests/test_utils.py
> +## the order of a list.
Yep, sets return things in whatever order they feel like, so `list(set(inputlist))` won't always return in the same order. You can tweak the underlying function to always return data in the same order - if you're only running this in python 3.7+, you can use the construction `list(dict.fromkeys(inputlist))`. If you're running this in anything less than 3.7 in addition to 3.7+, you can do this instead:
`from collections import OrderedDict`
`list(OrderedDict.fromkeys(inputlist))`

2021-01-22 18:09 UTC, kelockhart commented on ADSAffil/tests/test_utils.py
> +## the order of a list.
Meant to add this: https://stackoverflow.com/questions/7961363/removing-duplicates-in-the-lists

2021-01-25 19:00 UTC, seasidesparrow commented on requirements.txt
> -# Make sure 2nd level dependencies are python2 compatible:
Python 3 only -- this is mainly a refactor to simplify for Python3.

2021-01-25 20:04 UTC, seasidesparrow commented on ADSAffil/tasks.py
>      task_augment_affiliations_json(msg)
I didn't remember offhand, but I found this in the github history -- it's meant to pass records coming via master-pipeline through a different queue than records being updated via run.py: https://github.com/adsabs/ADSAffilPipeline/commit/9c56f1953574385df5e053a8bcf2074bfed63916#diff-3cf3281d2ebf14cd03d4b40b2bfeeb151ab46e3deded354d48c689981e4f15d4

2021-01-25 20:53 UTC, seasidesparrow commented on run.py
>      parser.add_argument('-f',
The curation library for affils is (soon) going to live here: https://github.com/adsabs/ADSCurateAffils.  I'll review tests here to add some more informative coverage.  The pickling process uses text files that are generated by hand, not from Solr.

2021-02-09 18:42 UTC, seasidesparrow commented on ADSAffil/app.py
> +        if self.instring:
The consequence of not having self.instring defined is that it will leave self.instring_norm undefined, and that's a valid state (caught in line 31 of the _match_affil function).

2021-02-09 19:01 UTC, seasidesparrow commented on ADSAffil/tests/test_utils.py
> +## the order of a list.
This has been fixed and stubdata updated.

2021-02-11 22:20 UTC, kelockhart approved these changes
Looks good!

2021-02-12 13:53 UTC, merged